version: "3.9"
services:
  database:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: turnos_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: turnos_db
      DB_PORT: 3306
      PORT: 4000
      CORS_ORIGIN: "*"
      JWT_SECRET: dev_secret
    ports:
      - "4000:4000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      - backend